// GENERATED by tool/apply_catalogue_categories.mjs from catalogue/categories.json.
// ignore_for_file: prefer_single_quotes
import '../../products/models/category.dart';

abstract final class CustomerCatalogCategories {
  static const all = <ProductCategory>[
    ProductCategory(
      id: "37d319bb-8aed-5955-8513-a192b36b0f88",
      name: "Dal",
      visualKey: "dal",
    ),
    ProductCategory(
      id: "b996b40a-0b79-55fd-a131-2ff1f0ec4a19",
      name: "Atta",
      visualKey: "atta",
    ),
    ProductCategory(
      id: "999485a7-918a-5e0b-81a2-c18511f78f06",
      name: "Grains",
      visualKey: "grains",
    ),
    ProductCategory(
      id: "6a7b7195-511b-5e8d-a0cd-bec03de91f7f",
      name: "Millets",
      visualKey: "millets",
    ),
    ProductCategory(
      id: "7ca32cfb-cdd4-5900-9c70-f9986802182b",
      name: "Masala Box",
      visualKey: "masala-box",
    ),
    ProductCategory(
      id: "26c3fced-d932-5ff6-bed2-986e4a73ebc0",
      name: "Garam Masalas",
      visualKey: "garam-masalas",
    ),
    ProductCategory(
      id: "58d712c3-a0e1-51a7-bba6-f3d218b594d2",
      name: "Cooking Oils",
      visualKey: "cooking-oils",
    ),
    ProductCategory(
      id: "6b929720-5435-55c5-81a2-55ea7f9e58bf",
      name: "Pooja Oils & Items",
      visualKey: "pooja",
    ),
    ProductCategory(
      id: "2a8dbca1-00e4-5da5-a3c4-87aa27e88976",
      name: "Papads",
      visualKey: "papads",
    ),
    ProductCategory(
      id: "58a50fcb-c5c9-5c8f-82c1-4a88f169ffe1",
      name: "Chocolates",
      visualKey: "chocolates",
    ),
    ProductCategory(
      id: "79a1e263-2e40-5064-bddd-96b10864067a",
      name: "Ice Creams",
      visualKey: "ice-creams",
    ),
    ProductCategory(
      id: "0b8a08e4-b399-5e18-bd7e-f6b8276d3564",
      name: "Spices",
      visualKey: "spices",
    ),
    ProductCategory(
      id: "140a7a0b-8b1c-5d95-b25c-264bf8853413",
      name: "Ghee",
      visualKey: "ghee",
    ),
    ProductCategory(
      id: "c3b4ec73-0291-51f5-9a2d-2a8ab2355a4b",
      name: "Biscuits",
      visualKey: "biscuits",
    ),
    ProductCategory(
      id: "11000000-0000-4000-8000-000000000009",
      name: "Home Care",
      visualKey: "household",
    ),
    ProductCategory(
      id: "2c8b2913-67a2-5981-8eb8-6d19b818abef",
      name: "Body Care",
      visualKey: "body-care",
    ),
    ProductCategory(
      id: "bb3d0154-bd12-5c40-a30c-d327152b754c",
      name: "Kids Care",
      visualKey: "kids-care",
    ),
    ProductCategory(
      id: "058a5632-27e9-5300-8f7a-998112e8715c",
      name: "Tea & Coffee",
      visualKey: "tea-coffee",
    ),
    ProductCategory(
      id: "a40c741c-c90a-543e-9eb8-f0505d8f5097",
      name: "Pain Reliefs",
      visualKey: "pain-relief",
    ),
    ProductCategory(
      id: "50dc2f98-83f9-5bc4-958c-c10f118e9d66",
      name: "Basmati",
      visualKey: "basmati",
    ),
    ProductCategory(
      id: "6793fc43-b72c-53f9-be76-b41fd81c95f6",
      name: "Sauces",
      visualKey: "sauces",
    ),
    ProductCategory(
      id: "64832232-8f84-5448-bca0-d2ace59a81e6",
      name: "Food Colour & Essences",
      visualKey: "food-colour",
    ),
    ProductCategory(
      id: "8fb9addb-3805-5d91-a08f-d48623611b41",
      name: "Detergents",
      visualKey: "detergents",
    ),
    ProductCategory(
      id: "5cde0efc-2c25-5a05-a0a4-bd207ec01ce8",
      name: "Fabric Care",
      visualKey: "fabric-care",
    ),
    ProductCategory(
      id: "4a1d987e-beba-54c8-9e7e-a39dd46c3378",
      name: "Dry Fruits & Nuts",
      visualKey: "dry-fruits",
    ),
    ProductCategory(
      id: "d268a6f2-6b0f-5a46-a8bf-e4bb47425c85",
      name: "Salt, Sugar & Jaggery",
      visualKey: "salt-sugar",
    ),
    ProductCategory(
      id: "ade0df1f-e8fb-5bd2-802b-233f2fe7db45",
      name: "Milk & Dairy",
      visualKey: "dairy",
    ),
    ProductCategory(
      id: "614bee6c-a8d1-55b3-b578-80080207e52f",
      name: "Breakfast & Cereals",
      visualKey: "breakfast",
    ),
    ProductCategory(
      id: "dd5b2aab-c519-5e7b-9a54-a6ce0e774a20",
      name: "Noodles & Pasta",
      visualKey: "pasta",
    ),
    ProductCategory(
      id: "21191bef-309d-5f06-9a92-10fb088b8786",
      name: "Baking Supplies",
      visualKey: "baking",
    ),
    ProductCategory(
      id: "28b3d638-f36a-562e-8d40-17759e9c0ff8",
      name: "Jam, Honey & Spreads",
      visualKey: "spreads",
    ),
    ProductCategory(
      id: "ae8ce70d-e047-52a0-b039-ec81eba37772",
      name: "Pickles & Chutneys",
      visualKey: "pickles",
    ),
    ProductCategory(
      id: "0a8544a2-7e83-5644-8486-5cd716cc0a48",
      name: "Snacks & Sweets",
      visualKey: "snacks",
    ),
    ProductCategory(
      id: "b6d15247-d621-51cf-933d-7857828c7d07",
      name: "Beverages",
      visualKey: "beverages",
    ),
    ProductCategory(
      id: "5f42ba97-5e93-5ed0-8ece-7afc5787cca2",
      name: "Health & Wellness",
      visualKey: "health",
    ),
    ProductCategory(
      id: "adce7d67-5c29-5b9d-be41-6f93a833baeb",
      name: "Household Essentials",
      visualKey: "general",
    ),
    ProductCategory(
      id: "189072e9-1d36-5470-b800-e202dc5eedba",
      name: "Fresh Vegetables",
      visualKey: "fresh",
    ),
  ];

  static String? visualForName(String name) {
    final normalized = name.trim().toLowerCase();
    for (final category in all) {
      if (category.name.toLowerCase() == normalized) return category.visualKey;
    }
    return null;
  }
}
