import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { categoryForProduct, categoryId } from './catalogue_categories.mjs';

const root = path.resolve(import.meta.dirname, '..');
const read = (file) => fs.readFile(path.join(root, file), 'utf8');
const definitions = JSON.parse(await read('catalogue/categories.json')).map((category, index) => ({
  ...category, id: category.id ?? categoryId(category.key), sortOrder: index + 1,
}));
const categories = new Map(definitions.map((c) => [c.key, c]));
assert.equal(categories.size, definitions.length);
const file = 'lib/features/store/data/generated_product_catalog.dart';
const before = await read(file);
const stringField = (block, key) => {
  const literal = block.match(new RegExp(`\\n      ${key}:\\s*("(?:[^"\\\\]|\\\\.)*"),`))?.[1];
  return literal ? JSON.parse(literal.replace(/\\\$/g, '$')) : '';
};
const dart = (value) => JSON.stringify(value).replace(/\$/g, '\\$');
const sql = (value) => "'" + String(value).replaceAll("'", "''") + "'";
const assignments = [];
const errors = [];
let after = before.replace(/    Product\(\n[\s\S]*?\n    \),/g, (block) => {
  const product = Object.fromEntries(['id','categoryId','name','billingName','subcategory'].map((key) => [key, stringField(block,key)]));
  let category;
  try { category = categories.get(categoryForProduct(product)); }
  catch (error) { errors.push(error.message); return block; }
  assert.ok(category);
  const changed = block
    .replace(/\n      categoryId: "[^"]+",/, `\n      categoryId: ${dart(category.id)},`)
    .replace(/\n      visualKey: "[^"]+",/, `\n      visualKey: ${dart(category.key)},`);
  const strip = (text) => text.replace(/\n      (?:categoryId|visualKey): "[^"]+",/g,'');
  assert.equal(strip(block), strip(changed), 'Only category IDs and visuals may change');
  assignments.push({productId: product.id, billingName: product.billingName, name: product.name,
    subcategory: product.subcategory, categoryId: category.id, category: category.name, key: category.key});
  return changed;
});
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }
assert.equal(assignments.length, Number(before.match(/customerProductCount = (\d+)/)[1]));
assert.equal(new Set(assignments.map((p) => p.productId)).size, assignments.length);
const counts = definitions.map((c) => ({name:c.name, products: assignments.filter((p) => p.categoryId===c.id).length}));
console.log(JSON.stringify(counts,null,2));
assert.ok(counts.every((c) => c.products > 0), 'Every published category must contain products');
if (process.argv.includes('--preview')) process.exit(0);

const categoryBlock = `  static const categories = CustomerCatalogCategories.all;`;
after = after.replace(/  static const categories = <ProductCategory>\[[\s\S]*?\n  \];/, categoryBlock)
  .replace("import '../../products/models/category.dart';", "import 'customer_catalog_categories.dart';");
const taxonomy = `// GENERATED by tool/apply_catalogue_categories.mjs from catalogue/categories.json.\nimport '../../products/models/category.dart';\n\nabstract final class CustomerCatalogCategories {\n  static const all = <ProductCategory>[\n${definitions.map((c) => `    ProductCategory(id: ${dart(c.id)}, name: ${dart(c.name)}, visualKey: ${dart(c.key)}),`).join('\n')}\n  ];\n\n  static String? visualForName(String name) {\n    final normalized = name.trim().toLowerCase();\n    for (final category in all) {\n      if (category.name.toLowerCase() == normalized) return category.visualKey;\n    }\n    return null;\n  }\n}\n`;
if (process.argv.includes('--check')) {
  assert.equal(after,before,'Category assignments are stale; run tool/apply_catalogue_categories.mjs');
  const existing = await read('lib/features/store/data/customer_catalog_categories.dart');
  for (const category of definitions) {
    assert.ok(existing.includes(dart(category.id)) && existing.includes(dart(category.name)) && existing.includes(dart(category.key)));
  }
  process.exit(0);
}
const write = (file, data) => fs.writeFile(path.join(root,file),data);
await write(file,after);
await write('lib/features/store/data/customer_catalog_categories.dart',taxonomy.replace('\nimport ', '\n// ignore_for_file: prefer_single_quotes\nimport '));
await write('catalogue/product_categories.json',JSON.stringify({reviewedAt:'2026-09-07',categories: definitions,assignments},null,2)+'\n');
const previousIds = Array.from({length:12},(_,i)=>`11000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`)
  .filter((id)=>!definitions.some((c)=>c.id===id));
const migration = `-- Client-requested catalogue categories, 2026-09-07.\n-- Category-only migration: preserve prices, stock, product IDs and order history.\n-- Prepared locally; apply through the normal Supabase deployment workflow.\nbegin;\n\ninsert into public.categories (id, name, sort_order, active) values\n${definitions.map((c)=>`  (${sql(c.id)}::uuid, ${sql(c.name)}, ${c.sortOrder}, true)`).join(',\n')}\non conflict (id) do update set name=excluded.name, sort_order=excluded.sort_order, active=true, updated_at=now();\n\nwith mapping(product_id, billing_name, category_id) as (values\n${assignments.map((p)=>`  (${sql(p.productId)}::uuid, ${sql(p.billingName)}, ${sql(p.categoryId)}::uuid)`).join(',\n')}\n)\nupdate public.products p set category_id=m.category_id\nfrom mapping m\nwhere p.id=m.product_id and p.source_product_name=m.billing_name\n  and p.category_id is distinct from m.category_id;\n\n-- Do not hide custom/unmatched live products which still use a legacy category.\nupdate public.categories c set active=false, updated_at=now()\nwhere c.id in (${previousIds.map(sql).join(', ')})\nand not exists (select 1 from public.products p where p.category_id=c.id and p.active);\n\ncommit;\n`;
await write('supabase/migrations/202609070001_client_catalogue_categories.sql',migration);
